# Copyright (C) 2024 Eternilab <support@eternilab.com>
#
# SPDX-License-Identifier: CECILL-2.1

---
stages:
  - linter

ansible-lint:
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  stage: linter
  tags:
    - linux
  script:
    - ansible-lint --version
    - ansible-lint --show-relpath

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  stage: linter
  tags:
    - linux
  script:
    - reuse lint
